spring.application.name=UrlShortener
#This will be overridden in production environments to use the appropriate profile (e.g., prod)
spring.profiles.active=local
#This is coming from the environment variable, which should be set in the deployment environment (e.g., Docker, Kubernetes, or railway variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true