spring.application.name=UrlShortener
spring.datasource.url=jdbc:postgresql://localhost:5000/Urls
spring.datasource.username=postgres
spring.datasource.password=Atharva#18
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true